export const REGIONS = [
  {
    id: 'kanto',
    name: 'Kanto',
    generation: 1,
    games: ['Pokémon Red/Blue/Yellow', 'FireRed/LeafGreen', 'Let\'s Go Pikachu/Eevee'],
    range: [1, 151],
    color: '#EF4444',
    emoji: '🗾',
    description: 'A região original, lar do Professor Carvalho e das primeiras aventuras Pokémon.',
    landmark: 'Monte Moon, Torre Pokémon, Ilha Cinábrio',
  },
  {
    id: 'johto',
    name: 'Johto',
    generation: 2,
    games: ['Pokémon Gold/Silver/Crystal', 'HeartGold/SoulSilver'],
    range: [152, 251],
    color: '#F59E0B',
    emoji: '🏯',
    description: 'Terra de tradições antigas e lendas místicas, conectada a Kanto.',
    landmark: 'Torre Ecruteak, Gruta Dragões, Lago Mágico',
  },
  {
    id: 'hoenn',
    name: 'Hoenn',
    generation: 3,
    games: ['Pokémon Ruby/Sapphire/Emerald', 'Omega Ruby/Alpha Sapphire'],
    range: [252, 386],
    color: '#3B82F6',
    emoji: '🌊',
    description: 'Região tropical cercada por oceanos, com muita chuva e sol.',
    landmark: 'Monte Chaminé, Cidade Pacifidlog, Ilha Mirage',
  },
  {
    id: 'sinnoh',
    name: 'Sinnoh',
    generation: 4,
    games: ['Pokémon Diamond/Pearl/Platinum', 'Brilliant Diamond/Shining Pearl'],
    range: [387, 493],
    color: '#6366F1',
    emoji: '⛰️',
    description: 'Região montanhosa com o mítico Monte Cornet ao centro.',
    landmark: 'Monte Cornet, Lago Acuity, Ruínas Solaceon',
  },
  {
    id: 'unova',
    name: 'Unova',
    generation: 5,
    games: ['Pokémon Black/White', 'Black 2/White 2'],
    range: [494, 649],
    color: '#8B5CF6',
    emoji: '🌆',
    description: 'Região inspirada em Nova York, com a vibrante Cidade Nuvema.',
    landmark: 'Ponte Skyarrow, Cidade Nacrene, Ruínas Relic',
  },
  {
    id: 'kalos',
    name: 'Kalos',
    generation: 6,
    games: ['Pokémon X/Y'],
    range: [650, 721],
    color: '#EC4899',
    emoji: '🗼',
    description: 'Região inspirada na França, famosa por beleza e moda.',
    landmark: 'Torre Prism, Cidade Lumiose, Floresta Parfum',
  },
  {
    id: 'alola',
    name: 'Alola',
    generation: 7,
    games: ['Pokémon Sun/Moon', 'Ultra Sun/Ultra Moon'],
    range: [722, 809],
    color: '#F97316',
    emoji: '🌺',
    description: 'Arquipélago tropical inspirado no Havaí, com tradições únicas.',
    landmark: 'Monte Lanakila, Altar da Sunne/Moone, Aether Paradise',
  },
  {
    id: 'galar',
    name: 'Galar',
    generation: 8,
    games: ['Pokémon Sword/Shield'],
    range: [810, 898],
    color: '#14B8A6',
    emoji: '⚔️',
    description: 'Região inspirada no Reino Unido, famosa pelos campeonatos Pokémon.',
    landmark: 'Floresta Glimwood, Campo Selvagem, Torre Galar',
  },
  {
    id: 'hisui',
    name: 'Hisui',
    generation: 8,
    games: ['Pokémon Legends: Arceus'],
    range: [899, 905],
    color: '#10B981',
    emoji: '🏔️',
    description: 'Versão ancestral de Sinnoh, no passado distante.',
    landmark: 'Monte Coronet, Aldeias Clan, Jubilfe Village',
  },
  {
    id: 'paldea',
    name: 'Paldea',
    generation: 9,
    games: ['Pokémon Scarlet/Violet'],
    range: [906, 1025],
    color: '#EF4444',
    emoji: '🌅',
    description: 'Região inspirada na Espanha/Portugal, com mundo aberto.',
    landmark: 'Great Crater of Paldea, Mesagoza Academy, Area Zero',
  },
]

export const HABITATS = [
  { id: 'forest',       name: 'Floresta',          emoji: '🌲', color: '#22C55E', description: 'Pokémon de florestas densas e bosques' },
  { id: 'mountain',     name: 'Montanha',           emoji: '⛰️', color: '#78716C', description: 'Pokémon de picos e encostas rochosas' },
  { id: 'cave',         name: 'Caverna',            emoji: '🕳️', color: '#57534E', description: 'Pokémon que habitam cavernas escuras' },
  { id: 'ocean',        name: 'Oceano',             emoji: '🌊', color: '#0EA5E9', description: 'Pokémon das profundezas marinhas' },
  { id: 'river',        name: 'Rio',                emoji: '🏞️', color: '#38BDF8', description: 'Pokémon de rios e correntezas' },
  { id: 'lake',         name: 'Lago',               emoji: '🏔️', color: '#7DD3FC', description: 'Pokémon de lagos tranquilos' },
  { id: 'city',         name: 'Cidade',             emoji: '🏙️', color: '#6B7280', description: 'Pokémon urbanos adaptados às cidades' },
  { id: 'grassland',    name: 'Campo',              emoji: '🌾', color: '#84CC16', description: 'Pokémon de planícies e pradarias' },
  { id: 'desert',       name: 'Deserto',            emoji: '🏜️', color: '#F59E0B', description: 'Pokémon de areais e terras áridas' },
  { id: 'volcano',      name: 'Vulcão',             emoji: '🌋', color: '#EF4444', description: 'Pokémon de ambientes vulcânicos' },
  { id: 'ice',          name: 'Gelo e Neve',        emoji: '❄️', color: '#BAE6FD', description: 'Pokémon de regiões geladas e árticas' },
  { id: 'sky',          name: 'Céu',                emoji: '☁️', color: '#E0F2FE', description: 'Pokémon que habitam o céu e nuvens' },
  { id: 'ruins',        name: 'Ruínas',             emoji: '🏛️', color: '#A78BFA', description: 'Pokémon de templos e ruínas antigas' },
  { id: 'swamp',        name: 'Pântano',            emoji: '🐸', color: '#4ADE80', description: 'Pokémon de pântanos e mangues' },
  { id: 'island',       name: 'Ilha',               emoji: '🏝️', color: '#34D399', description: 'Pokémon exclusivos de ilhas tropicais' },
  { id: 'dimension',    name: 'Dimensão Especial',  emoji: '🌀', color: '#818CF8', description: 'Pokémon de outras dimensões e distorção' },
]

export const getRegionByPokemonId = (id) => {
  return REGIONS.find(r => id >= r.range[0] && id <= r.range[1])
}
